### ISSUE TITLE
Can you help me detect if there is a human motion presence.

### ISSUE THREAD

**Issue by Prabindas001** [eloquentarduino/EloquentVision#2]

**Comment by eloquentarduino** [comment]
Try looking at this: https://create.arduino.cc/projecthub/little_lookout/person-detection-with-tensorflow-and-arduino-47ae01
I think you need Tensorflow for actual human detection. This library is not meant to distinguish the source of motion.

**Comment by Prabindas001** [comment]
I don't think an esp32 can do something similar to that was done by the Arduino nano 33 BLE sense as shown in the link you provided. I am stuck to detect human motion only while using a PIR. so I thought I can give it a try with esp32 cam and esp32. Please help me if you can.
