### ISSUE TITLE
Http output does not appear as an image

### ISSUE THREAD

**Issue by bill-orange** [eloquentarduino/EloquentVision#3]
When running the Video Streaming Server Example for an AI Thinker camera, rather than getting an image on the web page, I get continually scrolling random looking text.  It appears that the browser is not being instructed to interpret the output as an image or the image file is improper.

Thoughts?

**Comment by eloquentarduino** [comment]
I don't have an AI Thinker camera, but I will double-check on my M5Stick Camera and see what it could be. In the meantime, please open the Developer console (Ctrl + Maiusc + I in Google Chrome and Firefox), go to the network tab, locate the video request and paste here both the Request and Response headers.

**Comment by bill-orange** [comment]
Since my PC is a wired network connection, I tested the ESP-32-CAM HTTP output with my IPhone. Since I did not know how to get the Developer’s output from the IPhone’s browser, I connected with the laptop. On the laptop it works. I retested with the IPhone and it did not work side-by-side with the laptop where it did work. 

Here is the Developer’s output from the laptop.

**Comment by eloquentarduino** [comment]
This is probably due to a lack of support on the iOS, I think. Never used an iPhone, so please give me some time to check it out the supported video codecs.

PS: I don't see any Developer's output, but if it works, it shouldn't be of use to solve your problem.
