### ISSUE TITLE
Update to 0.4

### ISSUE THREAD

**Issue by MarkusTelser** [eloquentarduino/EloquentVision#6]
In io/JpegWriter a variable wasn't freed, this bug is already fixed, but the latest version was released before the fix. This causes my program to crash after ca. 50 calls, because every time va. 64 kb get allocated, but never freed. This makes the latest version in Arduino IDE library marketplace unusable. PLEASE UPDATE to new version, where this bug is fixed, so nobody has to waste houurs trying to find out, where memory is lost.

**Comment by eloquentarduino** [comment]
I'll push a new version to Arduino library manager later today.

**Comment by MarkusTelser** [comment]
thanks for the fast response :)

**Comment by eloquentarduino** [comment]
Pushed version 0.0.5 (I messed up with 0.0.4), should be available in the Library Manager in a few hours.
